version: "2"
services:
  crawler:
    image: mydemophpimage
    ports:
      - "80:80"
#    volumes:
#      - ./app:/var/www/html
    environment:
      SITE_URL: http://localhost
    networks:
      - test

networks:
  test:
    external: true